# StorageClass: Defines the type of storage and provisioner
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nginx-storage
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
parameters:
  type: gp3
  fsType: ext4
reclaimPolicy: Delete
allowVolumeExpansion: true
---
# PersistentVolume: Represents a piece of storage in the cluster
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-logs-pv
  labels:
    app: nginx
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nginx-storage
  awsElasticBlockStore:
    # This would need to be a real EBS volume ID in production
    # For demo purposes, we'll use the StorageClass instead
    volumeID: vol-xxxxxxxxxxxxxxxxx
    fsType: ext4