# RoleBinding: Grants the permissions defined in Role to users/groups/service accounts
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nginx-role-binding
  namespace: nginx-demo
  labels:
    app: nginx
subjects:
- kind: ServiceAccount
  name: nginx-service-account
  namespace: nginx-demo
roleRef:
  kind: Role
  name: nginx-role
  apiGroup: rbac.authorization.k8s.io
---
# ClusterRoleBinding: Grants cluster-wide permissions
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: nginx-cluster-role-binding
  labels:
    app: nginx
subjects:
- kind: ServiceAccount
  name: nginx-service-account
  namespace: nginx-demo
roleRef:
  kind: ClusterRole
  name: nginx-cluster-role
  apiGroup: rbac.authorization.k8s.io